stream:
  port: 9999
  healthCheck:
    endpoint: /health
  metrics:
    endpoint: /metrics
  instance:
    source:
      type: kafka
      specs:
        topic: draethos.inbound
        timeoutMs: 1000
        configurations:
          group.id: 'draethos5'
          bootstrap.servers: 'localhost:9093'
          auto.offset.reset: 'beginning'
          enable.auto.commit: false
    target:
      type: mysql
      specs:
        database: laravel
        table: extrac
        keyColumnName: id
        batchSize: 100
        configurations:
          host: '127.0.0.1'
          port: 3306
          user: 'laravel'
          password: 'root'
    dlq:
      type: kafka
      specs:
        topic: datalake.draethos.outbond.Dlq
        configurations:
          bootstrap.servers: 'localhost:9093'
