stream:
  port: 9999
  healthCheck:
    endpoint: /health
  metrics:
    endpoint: /metrics
  instance:
    source:
      type: kafka
      specs:
        topic: draethos.inbound
        timeoutMs: 10000
        configurations:
          group.id: 'draethos'
          bootstrap.servers: 'localhost:9093'
          auto.offset.reset: 'beginning'
          enable.auto.commit: false
    target:
      type: s3
      specs:
        bucket: payreport-qa
        prefix: '/topic_test_1/year=%{YEAR}/month=%{MONTH}/day=%{DAY}/hour=%{HOUR}/'
        codec: jsonl
        bufferSize: 10000
        flushInMilliseconds: 100000
        configurations:
          #aws.credential.file: ''
          #aws.profile: ''
          #aws.token: ''
          aws.access.key: ''
          aws.secret.key: ''
          aws.region: 'us-east-1'
    dlq:
      type: kafka
      specs:
        topic: topic_test_1_dlq
        configurations:
          bootstrap.servers: 'localhost:9093'
